app <- paste(readLines("app.R", warn = FALSE, encoding = "UTF-8"), collapse = "\n")
stopifnot(grepl('tab_about', app, fixed = TRUE))
stopifnot(grepl('output$about_ui', app, fixed = TRUE))
stopifnot(grepl('Universidade Federal do Rio Grande do Norte', app, fixed = TRUE))
stopifnot(grepl('Coordenação de Aperfeiçoamento de Pessoal de Nível Superior', app, fixed = TRUE))
stopifnot(grepl('Conselho Nacional de Desenvolvimento Científico e Tecnológico', app, fixed = TRUE))
stopifnot(grepl('Scientific transparency principle', app, fixed = TRUE))
stopifnot(grepl('Abrir artigo', app, fixed = TRUE))
stopifnot(grepl('Jaqueiuto S. Jorge e colaboradores', app, fixed = TRUE))
stopifnot(grepl('Jaqueiuto S. Jorge and collaborators', app, fixed = TRUE))
stopifnot(grepl('0000-0003-4887-3647', app, fixed = TRUE))
cat("Scientific/institutional information checks passed.\n")
