app <- paste(readLines("app.R", warn = FALSE, encoding = "UTF-8"), collapse = "\n")
stopifnot(grepl("evidence-toggle-btn", app, fixed = TRUE))
stopifnot(grepl("mg_evidence_panel_", app, fixed = TRUE))
stopifnot(grepl("aria-expanded", app, fixed = TRUE))
stopifnot(grepl("Ver evidências científicas", app, fixed = TRUE))
stopifnot(grepl("fontes científicas", app, fixed = TRUE))
stopifnot(grepl("diagnostic-summary", app, fixed = TRUE))
stopifnot(!grepl("tags$details(tags$summary", app, fixed = TRUE))
cat("Management evidence toggle checks passed.\n")
