stopifnot(file.exists("data/management_evidence_database.csv"))
stopifnot(file.exists("data/management_decision_rules.csv"))
stopifnot(file.exists("data/management_priority_matrix.csv"))
e <- read.csv("data/management_evidence_database.csv", stringsAsFactors=FALSE, check.names=FALSE)
r <- read.csv("data/management_decision_rules.csv", stringsAsFactors=FALSE, check.names=FALSE)
p <- read.csv("data/management_priority_matrix.csv", stringsAsFactors=FALSE, check.names=FALSE)
stopifnot(all(c("Evidence_ID","Management_ID","Evidence_strength","Reference","DOI","Caveats") %in% names(e)))
stopifnot(!anyDuplicated(e$Evidence_ID))
stopifnot(all(c("Context_variable","Context_response","Context_score") %in% names(r)))
stopifnot(all(r$Context_score %in% c(0,1,2)))
stopifnot(nrow(p)==12)
stopifnot(any(p$Exposure_ID=="E3" & p$Context_score==0 & p$Management_priority=="Moderate"))
stopifnot(any(r$Context_response=="Unknown" & r$Context_score==0))
cat("Management semantics checks passed.\n")
